# -*- coding: utf-8 -*-
"""Personal_Expense_tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJo-Y2LQ9QXSR_K1BY2oQw1VH4wynz_x
"""

import csv
import os
import datetime
import calendar

# Define the Expense class
class Expense:
    def __init__(self, name, amount, category, date):
        self.name = name
        self.amount = amount
        self.category = category
        self.date = date

    def __repr__(self):
        return f"Expense(Name: {self.name}, Amount: ₹{self.amount:.2f}, Category: {self.category}, Date: {self.date})"

# Function to validate date format
def validate_date(date_text):
    try:
        datetime.datetime.strptime(date_text, '%Y-%m-%d')
        return True
    except ValueError:
        return False

# Function to input monthly budget from user
def input_monthly_budget():
    while True:
        try:
            budget = float(input("Enter your monthly budget: ₹"))
            if budget <= 0:
                print("Budget must be greater than zero.")
                continue
            return budget
        except ValueError:
            print("Invalid input. Please enter a numeric value.")

# Function to add an expense
def add_expense():
    name = input("Enter expense description: ")
    try:
        amount = float(input("Enter amount: "))
    except ValueError:
        print("Invalid amount. Please enter a number.")
        return None

    category = input("Enter category (Food, Home, Work, Entertainment, Misc): ")
    date = input("Enter date (YYYY-MM-DD): ")

    if not all([name.strip(), category.strip(), date.strip()]):
        print("Missing one or more required fields. Entry skipped.")
        return None

    if not validate_date(date):
        print("Invalid date format. Use YYYY-MM-DD.")
        return None

    return Expense(name, amount, category, date)

# Function to load expenses from CSV file
def load_expenses(file_path):
    expenses = []
    if os.path.exists(file_path):
        with open(file_path, mode='r') as file:
            reader = csv.DictReader(file)
            for row in reader:
                if row['Name'] and row['Amount'] and row['Category'] and row['Date']:
                    if validate_date(row['Date']):
                        try:
                            expenses.append(Expense(row['Name'], float(row['Amount']), row['Category'], row['Date']))
                        except ValueError:
                            print(f"Skipping entry with invalid amount: {row}")
                    else:
                        print(f"Skipping entry with invalid date: {row}")
                else:
                    print(f"Skipping incomplete entry: {row}")
    return expenses

# Function to load monthly budget from file
def load_budget(budget_path):
    if os.path.exists(budget_path):
        with open(budget_path, 'r') as file:
            try:
                return float(file.read())
            except ValueError:
                return input_monthly_budget()
    else:
        return input_monthly_budget()

# Function to save monthly budget to file
def save_budget(budget, budget_path):
    with open(budget_path, 'w') as file:
        file.write(str(budget))

# Function to save expenses to CSV file
def save_expenses(expenses, file_path):
    with open(file_path, mode='w', newline='') as file:
        fieldnames = ['Name', 'Amount', 'Category', 'Date']
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        for exp in expenses:
            writer.writerow({'Name': exp.name, 'Amount': exp.amount, 'Category': exp.category, 'Date': exp.date})

# Function to view all expenses
def view_expenses(expenses):
    if not expenses:
        print("\nNo expenses recorded yet.")
    else:
        print("\nAll Expenses:")
        for exp in expenses:
            if all([exp.name, exp.amount, exp.category, exp.date]) and validate_date(exp.date):
                print(exp)
            else:
                print(f"Skipping invalid or incomplete entry: {exp}")

# Function to calculate total expenses
def calculate_total_expenses(expenses):
    return sum(exp.amount for exp in expenses)

# Function to track the budget
def track_budget(expenses, monthly_budget):
    total = calculate_total_expenses(expenses)
    print(f"\nTotal Expenses: ₹{total:.2f}")
    if total > monthly_budget:
        print("Warning: You have exceeded your budget!")
    else:
        print(f"You have ₹{monthly_budget - total:.2f} left for the month.")

# Function to display the menu
def display_menu():
    print("\n===== Personal Expense Tracker Menu =====")
    print("1. Add Expense")
    print("2. View Expenses")
    print("3. Track Budget")
    print("4. Save Expenses")
    print("5. Exit")

# Main function to run the program
def main():
    file_path = 'expenses.csv'
    budget_path = 'budget.txt'

    expenses = load_expenses(file_path)
    monthly_budget = load_budget(budget_path)

    while True:
        display_menu()
        choice = input("Select an option (1-5): ")

        if choice == '1':
            expense = add_expense()
            if expense:
                expenses.append(expense)
        elif choice == '2':
            view_expenses(expenses)
        elif choice == '3':
            track_budget(expenses, monthly_budget)
        elif choice == '4':
            save_expenses(expenses, file_path)
            save_budget(monthly_budget, budget_path)
            print("Expenses and budget saved successfully!")
        elif choice == '5':
            print("Exiting... Goodbye!")
            break
        else:
            print("Invalid choice. Please select a valid option.")

if __name__ == '__main__':
    main()

